
on: pull_request
name: dockerfile linting
jobs:
  dockerfilelint:
    name: dockerfile lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - name: hadolint
      uses: burdzwastaken/hadolint-action@1.14.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HADOLINT_ACTION_DOCKERFILE_FOLDER: .
  
  dockerbuild:
    name: docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.6
    - name: extract tag
      id: vars
      run: echo ::set-output name=alpine_version::$(grep '^FROM alpine' Dockerfile  | cut -d ' ' -f 2 | cut -d ':' -f 2)

    - name: docker build
      run: docker build . --file Dockerfile --tag image:${{ steps.vars.outputs.alpine_version }}

  approve:
    name: Dependabot PR Auto-approve
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v3.2.1
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
